version: '3'
services:
  ejprd-qb-index:
    build:
      context: .
    image: ejprd/qb-index
    restart: unless-stopped
    volumes:
      - ./application.yml:/app/application.yml:ro
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
