version: '3'

services:
  #  ejprdindex service
  ejprdindex:
    build:
      context: .
      dockerfile: Dockerfile
    image: ejprdindex
    restart: always
    hostname: ejprdindex
    ports:
      - 8000:8080
    volumes:
      - ./application.yml:/app/application.yml:ro
